/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateAdminRouteRouteImport } from './routes/_private/admin/route'
import { Route as PrivateSettingsRouteImport } from './routes/_private/settings'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicPolicyRouteImport } from './routes/_public/policy'
import { Route as PublicSubsRouteImport } from './routes/_public/subs'
import { Route as PublicUnsubscribeRouteImport } from './routes/_public/unsubscribe'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthWelcomeRouteImport } from './routes/auth/welcome'
import { Route as PrivateAdminBugReportsRouteImport } from './routes/_private/admin/bug-reports'
import { Route as PrivateAdminKiosksRouteImport } from './routes/_private/admin/kiosks'
import { Route as PrivateAdminRolesRouteImport } from './routes/_private/admin/roles'
import { Route as PrivateAdminUsersRouteImport } from './routes/_private/admin/users'
import { Route as PrivateCardsIndexRouteImport } from './routes/_private/cards/index'
import { Route as PrivateAdminDevNotificationsRouteImport } from './routes/_private/admin/dev/notifications'
import { Route as PrivateAdminDoorlockIndexRouteImport } from './routes/_private/admin/doorlock/index'
import { Route as PrivateAdminDoorlockCardsRouteImport } from './routes/_private/admin/doorlock/cards'
import { Route as PrivateAdminDoorlockDevicesRouteImport } from './routes/_private/admin/doorlock/devices'
import { Route as PrivateAdminDoorlockLogsRouteImport } from './routes/_private/admin/doorlock/logs'
import { Route as PrivateAdminNavigatorIndexRouteImport } from './routes/_private/admin/navigator/index'
import { Route as PrivateAdminNavigatorBuildingsRouteImport } from './routes/_private/admin/navigator/buildings'
import { Route as PrivateAdminNavigatorClassroomTypesRouteImport } from './routes/_private/admin/navigator/classroom-types'
import { Route as PrivateAdminNavigatorClassroomsRouteImport } from './routes/_private/admin/navigator/classrooms'
import { Route as PrivateAdminNavigatorCorridorsRouteImport } from './routes/_private/admin/navigator/corridors'
import { Route as PrivateAdminNavigatorLiftsRouteImport } from './routes/_private/admin/navigator/lifts'
import { Route as PrivateAdminNavigatorPreviewRouteImport } from './routes/_private/admin/navigator/preview'
import { Route as PrivateAdminNavigatorStairsRouteImport } from './routes/_private/admin/navigator/stairs'
import { Route as PrivateAdminNavigatorTranslationsRouteImport } from './routes/_private/admin/navigator/translations'
import { Route as PrivateAdminNewsAnnouncementsRouteImport } from './routes/_private/admin/news/announcements'
import { Route as PrivateAdminNewsSystemMessagesRouteImport } from './routes/_private/admin/news/system-messages'
import { Route as PrivateAdminTimetableImportRouteImport } from './routes/_private/admin/timetable/import'
import { Route as PrivateAdminTimetableManageRouteImport } from './routes/_private/admin/timetable/manage'
import { Route as PrivateAdminTimetableMovedLessonsRouteImport } from './routes/_private/admin/timetable/moved-lessons'
import { Route as PrivateAdminTimetableSubstitutionsRouteImport } from './routes/_private/admin/timetable/substitutions'
import { Route as PrivateAdminTimetableTeachersRouteImport } from './routes/_private/admin/timetable/teachers'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAdminRouteRoute = PrivateAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPolicyRoute = PublicPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSubsRoute = PublicSubsRouteImport.update({
  id: '/subs',
  path: '/subs',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicUnsubscribeRoute = PublicUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/auth/welcome',
  path: '/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAdminBugReportsRoute = PrivateAdminBugReportsRouteImport.update({
  id: '/bug-reports',
  path: '/bug-reports',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminKiosksRoute = PrivateAdminKiosksRouteImport.update({
  id: '/kiosks',
  path: '/kiosks',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminRolesRoute = PrivateAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminUsersRoute = PrivateAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateCardsIndexRoute = PrivateCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminDevNotificationsRoute =
  PrivateAdminDevNotificationsRouteImport.update({
    id: '/dev/notifications',
    path: '/dev/notifications',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminDoorlockIndexRoute =
  PrivateAdminDoorlockIndexRouteImport.update({
    id: '/doorlock/',
    path: '/doorlock/',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminDoorlockCardsRoute =
  PrivateAdminDoorlockCardsRouteImport.update({
    id: '/doorlock/cards',
    path: '/doorlock/cards',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminDoorlockDevicesRoute =
  PrivateAdminDoorlockDevicesRouteImport.update({
    id: '/doorlock/devices',
    path: '/doorlock/devices',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminDoorlockLogsRoute =
  PrivateAdminDoorlockLogsRouteImport.update({
    id: '/doorlock/logs',
    path: '/doorlock/logs',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorIndexRoute =
  PrivateAdminNavigatorIndexRouteImport.update({
    id: '/navigator/',
    path: '/navigator/',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorBuildingsRoute =
  PrivateAdminNavigatorBuildingsRouteImport.update({
    id: '/navigator/buildings',
    path: '/navigator/buildings',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorClassroomTypesRoute =
  PrivateAdminNavigatorClassroomTypesRouteImport.update({
    id: '/navigator/classroom-types',
    path: '/navigator/classroom-types',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorClassroomsRoute =
  PrivateAdminNavigatorClassroomsRouteImport.update({
    id: '/navigator/classrooms',
    path: '/navigator/classrooms',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorCorridorsRoute =
  PrivateAdminNavigatorCorridorsRouteImport.update({
    id: '/navigator/corridors',
    path: '/navigator/corridors',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorLiftsRoute =
  PrivateAdminNavigatorLiftsRouteImport.update({
    id: '/navigator/lifts',
    path: '/navigator/lifts',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorPreviewRoute =
  PrivateAdminNavigatorPreviewRouteImport.update({
    id: '/navigator/preview',
    path: '/navigator/preview',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorStairsRoute =
  PrivateAdminNavigatorStairsRouteImport.update({
    id: '/navigator/stairs',
    path: '/navigator/stairs',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNavigatorTranslationsRoute =
  PrivateAdminNavigatorTranslationsRouteImport.update({
    id: '/navigator/translations',
    path: '/navigator/translations',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNewsAnnouncementsRoute =
  PrivateAdminNewsAnnouncementsRouteImport.update({
    id: '/news/announcements',
    path: '/news/announcements',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminNewsSystemMessagesRoute =
  PrivateAdminNewsSystemMessagesRouteImport.update({
    id: '/news/system-messages',
    path: '/news/system-messages',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminTimetableImportRoute =
  PrivateAdminTimetableImportRouteImport.update({
    id: '/timetable/import',
    path: '/timetable/import',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminTimetableManageRoute =
  PrivateAdminTimetableManageRouteImport.update({
    id: '/timetable/manage',
    path: '/timetable/manage',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminTimetableMovedLessonsRoute =
  PrivateAdminTimetableMovedLessonsRouteImport.update({
    id: '/timetable/moved-lessons',
    path: '/timetable/moved-lessons',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminTimetableSubstitutionsRoute =
  PrivateAdminTimetableSubstitutionsRouteImport.update({
    id: '/timetable/substitutions',
    path: '/timetable/substitutions',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminTimetableTeachersRoute =
  PrivateAdminTimetableTeachersRouteImport.update({
    id: '/timetable/teachers',
    path: '/timetable/teachers',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/settings': typeof PrivateSettingsRoute
  '/policy': typeof PublicPolicyRoute
  '/subs': typeof PublicSubsRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/admin/bug-reports': typeof PrivateAdminBugReportsRoute
  '/admin/kiosks': typeof PrivateAdminKiosksRoute
  '/admin/roles': typeof PrivateAdminRolesRoute
  '/admin/users': typeof PrivateAdminUsersRoute
  '/cards/': typeof PrivateCardsIndexRoute
  '/admin/dev/notifications': typeof PrivateAdminDevNotificationsRoute
  '/admin/doorlock/cards': typeof PrivateAdminDoorlockCardsRoute
  '/admin/doorlock/devices': typeof PrivateAdminDoorlockDevicesRoute
  '/admin/doorlock/logs': typeof PrivateAdminDoorlockLogsRoute
  '/admin/navigator/buildings': typeof PrivateAdminNavigatorBuildingsRoute
  '/admin/navigator/classroom-types': typeof PrivateAdminNavigatorClassroomTypesRoute
  '/admin/navigator/classrooms': typeof PrivateAdminNavigatorClassroomsRoute
  '/admin/navigator/corridors': typeof PrivateAdminNavigatorCorridorsRoute
  '/admin/navigator/lifts': typeof PrivateAdminNavigatorLiftsRoute
  '/admin/navigator/preview': typeof PrivateAdminNavigatorPreviewRoute
  '/admin/navigator/stairs': typeof PrivateAdminNavigatorStairsRoute
  '/admin/navigator/translations': typeof PrivateAdminNavigatorTranslationsRoute
  '/admin/news/announcements': typeof PrivateAdminNewsAnnouncementsRoute
  '/admin/news/system-messages': typeof PrivateAdminNewsSystemMessagesRoute
  '/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
  '/admin/timetable/manage': typeof PrivateAdminTimetableManageRoute
  '/admin/timetable/moved-lessons': typeof PrivateAdminTimetableMovedLessonsRoute
  '/admin/timetable/substitutions': typeof PrivateAdminTimetableSubstitutionsRoute
  '/admin/timetable/teachers': typeof PrivateAdminTimetableTeachersRoute
  '/admin/doorlock/': typeof PrivateAdminDoorlockIndexRoute
  '/admin/navigator/': typeof PrivateAdminNavigatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/settings': typeof PrivateSettingsRoute
  '/policy': typeof PublicPolicyRoute
  '/subs': typeof PublicSubsRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/admin/bug-reports': typeof PrivateAdminBugReportsRoute
  '/admin/kiosks': typeof PrivateAdminKiosksRoute
  '/admin/roles': typeof PrivateAdminRolesRoute
  '/admin/users': typeof PrivateAdminUsersRoute
  '/cards': typeof PrivateCardsIndexRoute
  '/admin/dev/notifications': typeof PrivateAdminDevNotificationsRoute
  '/admin/doorlock/cards': typeof PrivateAdminDoorlockCardsRoute
  '/admin/doorlock/devices': typeof PrivateAdminDoorlockDevicesRoute
  '/admin/doorlock/logs': typeof PrivateAdminDoorlockLogsRoute
  '/admin/navigator/buildings': typeof PrivateAdminNavigatorBuildingsRoute
  '/admin/navigator/classroom-types': typeof PrivateAdminNavigatorClassroomTypesRoute
  '/admin/navigator/classrooms': typeof PrivateAdminNavigatorClassroomsRoute
  '/admin/navigator/corridors': typeof PrivateAdminNavigatorCorridorsRoute
  '/admin/navigator/lifts': typeof PrivateAdminNavigatorLiftsRoute
  '/admin/navigator/preview': typeof PrivateAdminNavigatorPreviewRoute
  '/admin/navigator/stairs': typeof PrivateAdminNavigatorStairsRoute
  '/admin/navigator/translations': typeof PrivateAdminNavigatorTranslationsRoute
  '/admin/news/announcements': typeof PrivateAdminNewsAnnouncementsRoute
  '/admin/news/system-messages': typeof PrivateAdminNewsSystemMessagesRoute
  '/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
  '/admin/timetable/manage': typeof PrivateAdminTimetableManageRoute
  '/admin/timetable/moved-lessons': typeof PrivateAdminTimetableMovedLessonsRoute
  '/admin/timetable/substitutions': typeof PrivateAdminTimetableSubstitutionsRoute
  '/admin/timetable/teachers': typeof PrivateAdminTimetableTeachersRoute
  '/admin/doorlock': typeof PrivateAdminDoorlockIndexRoute
  '/admin/navigator': typeof PrivateAdminNavigatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/admin': typeof PrivateAdminRouteRouteWithChildren
  '/_private/settings': typeof PrivateSettingsRoute
  '/_public/policy': typeof PublicPolicyRoute
  '/_public/subs': typeof PublicSubsRoute
  '/_public/unsubscribe': typeof PublicUnsubscribeRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/admin/bug-reports': typeof PrivateAdminBugReportsRoute
  '/_private/admin/kiosks': typeof PrivateAdminKiosksRoute
  '/_private/admin/roles': typeof PrivateAdminRolesRoute
  '/_private/admin/users': typeof PrivateAdminUsersRoute
  '/_private/cards/': typeof PrivateCardsIndexRoute
  '/_private/admin/dev/notifications': typeof PrivateAdminDevNotificationsRoute
  '/_private/admin/doorlock/cards': typeof PrivateAdminDoorlockCardsRoute
  '/_private/admin/doorlock/devices': typeof PrivateAdminDoorlockDevicesRoute
  '/_private/admin/doorlock/logs': typeof PrivateAdminDoorlockLogsRoute
  '/_private/admin/navigator/buildings': typeof PrivateAdminNavigatorBuildingsRoute
  '/_private/admin/navigator/classroom-types': typeof PrivateAdminNavigatorClassroomTypesRoute
  '/_private/admin/navigator/classrooms': typeof PrivateAdminNavigatorClassroomsRoute
  '/_private/admin/navigator/corridors': typeof PrivateAdminNavigatorCorridorsRoute
  '/_private/admin/navigator/lifts': typeof PrivateAdminNavigatorLiftsRoute
  '/_private/admin/navigator/preview': typeof PrivateAdminNavigatorPreviewRoute
  '/_private/admin/navigator/stairs': typeof PrivateAdminNavigatorStairsRoute
  '/_private/admin/navigator/translations': typeof PrivateAdminNavigatorTranslationsRoute
  '/_private/admin/news/announcements': typeof PrivateAdminNewsAnnouncementsRoute
  '/_private/admin/news/system-messages': typeof PrivateAdminNewsSystemMessagesRoute
  '/_private/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
  '/_private/admin/timetable/manage': typeof PrivateAdminTimetableManageRoute
  '/_private/admin/timetable/moved-lessons': typeof PrivateAdminTimetableMovedLessonsRoute
  '/_private/admin/timetable/substitutions': typeof PrivateAdminTimetableSubstitutionsRoute
  '/_private/admin/timetable/teachers': typeof PrivateAdminTimetableTeachersRoute
  '/_private/admin/doorlock/': typeof PrivateAdminDoorlockIndexRoute
  '/_private/admin/navigator/': typeof PrivateAdminNavigatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/policy'
    | '/subs'
    | '/unsubscribe'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/admin/bug-reports'
    | '/admin/kiosks'
    | '/admin/roles'
    | '/admin/users'
    | '/cards/'
    | '/admin/dev/notifications'
    | '/admin/doorlock/cards'
    | '/admin/doorlock/devices'
    | '/admin/doorlock/logs'
    | '/admin/navigator/buildings'
    | '/admin/navigator/classroom-types'
    | '/admin/navigator/classrooms'
    | '/admin/navigator/corridors'
    | '/admin/navigator/lifts'
    | '/admin/navigator/preview'
    | '/admin/navigator/stairs'
    | '/admin/navigator/translations'
    | '/admin/news/announcements'
    | '/admin/news/system-messages'
    | '/admin/timetable/import'
    | '/admin/timetable/manage'
    | '/admin/timetable/moved-lessons'
    | '/admin/timetable/substitutions'
    | '/admin/timetable/teachers'
    | '/admin/doorlock/'
    | '/admin/navigator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/settings'
    | '/policy'
    | '/subs'
    | '/unsubscribe'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/admin/bug-reports'
    | '/admin/kiosks'
    | '/admin/roles'
    | '/admin/users'
    | '/cards'
    | '/admin/dev/notifications'
    | '/admin/doorlock/cards'
    | '/admin/doorlock/devices'
    | '/admin/doorlock/logs'
    | '/admin/navigator/buildings'
    | '/admin/navigator/classroom-types'
    | '/admin/navigator/classrooms'
    | '/admin/navigator/corridors'
    | '/admin/navigator/lifts'
    | '/admin/navigator/preview'
    | '/admin/navigator/stairs'
    | '/admin/navigator/translations'
    | '/admin/news/announcements'
    | '/admin/news/system-messages'
    | '/admin/timetable/import'
    | '/admin/timetable/manage'
    | '/admin/timetable/moved-lessons'
    | '/admin/timetable/substitutions'
    | '/admin/timetable/teachers'
    | '/admin/doorlock'
    | '/admin/navigator'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/admin'
    | '/_private/settings'
    | '/_public/policy'
    | '/_public/subs'
    | '/_public/unsubscribe'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/_public/'
    | '/_private/admin/bug-reports'
    | '/_private/admin/kiosks'
    | '/_private/admin/roles'
    | '/_private/admin/users'
    | '/_private/cards/'
    | '/_private/admin/dev/notifications'
    | '/_private/admin/doorlock/cards'
    | '/_private/admin/doorlock/devices'
    | '/_private/admin/doorlock/logs'
    | '/_private/admin/navigator/buildings'
    | '/_private/admin/navigator/classroom-types'
    | '/_private/admin/navigator/classrooms'
    | '/_private/admin/navigator/corridors'
    | '/_private/admin/navigator/lifts'
    | '/_private/admin/navigator/preview'
    | '/_private/admin/navigator/stairs'
    | '/_private/admin/navigator/translations'
    | '/_private/admin/news/announcements'
    | '/_private/admin/news/system-messages'
    | '/_private/admin/timetable/import'
    | '/_private/admin/timetable/manage'
    | '/_private/admin/timetable/moved-lessons'
    | '/_private/admin/timetable/substitutions'
    | '/_private/admin/timetable/teachers'
    | '/_private/admin/doorlock/'
    | '/_private/admin/navigator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/admin': {
      id: '/_private/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/policy': {
      id: '/_public/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PublicPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/subs': {
      id: '/_public/subs'
      path: '/subs'
      fullPath: '/subs'
      preLoaderRoute: typeof PublicSubsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/unsubscribe': {
      id: '/_public/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof PublicUnsubscribeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/welcome': {
      id: '/auth/welcome'
      path: '/auth/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/admin/bug-reports': {
      id: '/_private/admin/bug-reports'
      path: '/bug-reports'
      fullPath: '/admin/bug-reports'
      preLoaderRoute: typeof PrivateAdminBugReportsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/kiosks': {
      id: '/_private/admin/kiosks'
      path: '/kiosks'
      fullPath: '/admin/kiosks'
      preLoaderRoute: typeof PrivateAdminKiosksRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/roles': {
      id: '/_private/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof PrivateAdminRolesRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/users': {
      id: '/_private/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof PrivateAdminUsersRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/cards/': {
      id: '/_private/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof PrivateCardsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin/dev/notifications': {
      id: '/_private/admin/dev/notifications'
      path: '/dev/notifications'
      fullPath: '/admin/dev/notifications'
      preLoaderRoute: typeof PrivateAdminDevNotificationsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/doorlock/': {
      id: '/_private/admin/doorlock/'
      path: '/doorlock'
      fullPath: '/admin/doorlock/'
      preLoaderRoute: typeof PrivateAdminDoorlockIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/doorlock/cards': {
      id: '/_private/admin/doorlock/cards'
      path: '/doorlock/cards'
      fullPath: '/admin/doorlock/cards'
      preLoaderRoute: typeof PrivateAdminDoorlockCardsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/doorlock/devices': {
      id: '/_private/admin/doorlock/devices'
      path: '/doorlock/devices'
      fullPath: '/admin/doorlock/devices'
      preLoaderRoute: typeof PrivateAdminDoorlockDevicesRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/doorlock/logs': {
      id: '/_private/admin/doorlock/logs'
      path: '/doorlock/logs'
      fullPath: '/admin/doorlock/logs'
      preLoaderRoute: typeof PrivateAdminDoorlockLogsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/': {
      id: '/_private/admin/navigator/'
      path: '/navigator'
      fullPath: '/admin/navigator/'
      preLoaderRoute: typeof PrivateAdminNavigatorIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/buildings': {
      id: '/_private/admin/navigator/buildings'
      path: '/navigator/buildings'
      fullPath: '/admin/navigator/buildings'
      preLoaderRoute: typeof PrivateAdminNavigatorBuildingsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/classroom-types': {
      id: '/_private/admin/navigator/classroom-types'
      path: '/navigator/classroom-types'
      fullPath: '/admin/navigator/classroom-types'
      preLoaderRoute: typeof PrivateAdminNavigatorClassroomTypesRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/classrooms': {
      id: '/_private/admin/navigator/classrooms'
      path: '/navigator/classrooms'
      fullPath: '/admin/navigator/classrooms'
      preLoaderRoute: typeof PrivateAdminNavigatorClassroomsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/corridors': {
      id: '/_private/admin/navigator/corridors'
      path: '/navigator/corridors'
      fullPath: '/admin/navigator/corridors'
      preLoaderRoute: typeof PrivateAdminNavigatorCorridorsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/lifts': {
      id: '/_private/admin/navigator/lifts'
      path: '/navigator/lifts'
      fullPath: '/admin/navigator/lifts'
      preLoaderRoute: typeof PrivateAdminNavigatorLiftsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/preview': {
      id: '/_private/admin/navigator/preview'
      path: '/navigator/preview'
      fullPath: '/admin/navigator/preview'
      preLoaderRoute: typeof PrivateAdminNavigatorPreviewRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/stairs': {
      id: '/_private/admin/navigator/stairs'
      path: '/navigator/stairs'
      fullPath: '/admin/navigator/stairs'
      preLoaderRoute: typeof PrivateAdminNavigatorStairsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/navigator/translations': {
      id: '/_private/admin/navigator/translations'
      path: '/navigator/translations'
      fullPath: '/admin/navigator/translations'
      preLoaderRoute: typeof PrivateAdminNavigatorTranslationsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/news/announcements': {
      id: '/_private/admin/news/announcements'
      path: '/news/announcements'
      fullPath: '/admin/news/announcements'
      preLoaderRoute: typeof PrivateAdminNewsAnnouncementsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/news/system-messages': {
      id: '/_private/admin/news/system-messages'
      path: '/news/system-messages'
      fullPath: '/admin/news/system-messages'
      preLoaderRoute: typeof PrivateAdminNewsSystemMessagesRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/timetable/import': {
      id: '/_private/admin/timetable/import'
      path: '/timetable/import'
      fullPath: '/admin/timetable/import'
      preLoaderRoute: typeof PrivateAdminTimetableImportRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/timetable/manage': {
      id: '/_private/admin/timetable/manage'
      path: '/timetable/manage'
      fullPath: '/admin/timetable/manage'
      preLoaderRoute: typeof PrivateAdminTimetableManageRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/timetable/moved-lessons': {
      id: '/_private/admin/timetable/moved-lessons'
      path: '/timetable/moved-lessons'
      fullPath: '/admin/timetable/moved-lessons'
      preLoaderRoute: typeof PrivateAdminTimetableMovedLessonsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/timetable/substitutions': {
      id: '/_private/admin/timetable/substitutions'
      path: '/timetable/substitutions'
      fullPath: '/admin/timetable/substitutions'
      preLoaderRoute: typeof PrivateAdminTimetableSubstitutionsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/timetable/teachers': {
      id: '/_private/admin/timetable/teachers'
      path: '/timetable/teachers'
      fullPath: '/admin/timetable/teachers'
      preLoaderRoute: typeof PrivateAdminTimetableTeachersRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
  }
}

interface PrivateAdminRouteRouteChildren {
  PrivateAdminBugReportsRoute: typeof PrivateAdminBugReportsRoute
  PrivateAdminKiosksRoute: typeof PrivateAdminKiosksRoute
  PrivateAdminRolesRoute: typeof PrivateAdminRolesRoute
  PrivateAdminUsersRoute: typeof PrivateAdminUsersRoute
  PrivateAdminDevNotificationsRoute: typeof PrivateAdminDevNotificationsRoute
  PrivateAdminDoorlockCardsRoute: typeof PrivateAdminDoorlockCardsRoute
  PrivateAdminDoorlockDevicesRoute: typeof PrivateAdminDoorlockDevicesRoute
  PrivateAdminDoorlockLogsRoute: typeof PrivateAdminDoorlockLogsRoute
  PrivateAdminNavigatorBuildingsRoute: typeof PrivateAdminNavigatorBuildingsRoute
  PrivateAdminNavigatorClassroomTypesRoute: typeof PrivateAdminNavigatorClassroomTypesRoute
  PrivateAdminNavigatorClassroomsRoute: typeof PrivateAdminNavigatorClassroomsRoute
  PrivateAdminNavigatorCorridorsRoute: typeof PrivateAdminNavigatorCorridorsRoute
  PrivateAdminNavigatorLiftsRoute: typeof PrivateAdminNavigatorLiftsRoute
  PrivateAdminNavigatorPreviewRoute: typeof PrivateAdminNavigatorPreviewRoute
  PrivateAdminNavigatorStairsRoute: typeof PrivateAdminNavigatorStairsRoute
  PrivateAdminNavigatorTranslationsRoute: typeof PrivateAdminNavigatorTranslationsRoute
  PrivateAdminNewsAnnouncementsRoute: typeof PrivateAdminNewsAnnouncementsRoute
  PrivateAdminNewsSystemMessagesRoute: typeof PrivateAdminNewsSystemMessagesRoute
  PrivateAdminTimetableImportRoute: typeof PrivateAdminTimetableImportRoute
  PrivateAdminTimetableManageRoute: typeof PrivateAdminTimetableManageRoute
  PrivateAdminTimetableMovedLessonsRoute: typeof PrivateAdminTimetableMovedLessonsRoute
  PrivateAdminTimetableSubstitutionsRoute: typeof PrivateAdminTimetableSubstitutionsRoute
  PrivateAdminTimetableTeachersRoute: typeof PrivateAdminTimetableTeachersRoute
  PrivateAdminDoorlockIndexRoute: typeof PrivateAdminDoorlockIndexRoute
  PrivateAdminNavigatorIndexRoute: typeof PrivateAdminNavigatorIndexRoute
}

const PrivateAdminRouteRouteChildren: PrivateAdminRouteRouteChildren = {
  PrivateAdminBugReportsRoute: PrivateAdminBugReportsRoute,
  PrivateAdminKiosksRoute: PrivateAdminKiosksRoute,
  PrivateAdminRolesRoute: PrivateAdminRolesRoute,
  PrivateAdminUsersRoute: PrivateAdminUsersRoute,
  PrivateAdminDevNotificationsRoute: PrivateAdminDevNotificationsRoute,
  PrivateAdminDoorlockCardsRoute: PrivateAdminDoorlockCardsRoute,
  PrivateAdminDoorlockDevicesRoute: PrivateAdminDoorlockDevicesRoute,
  PrivateAdminDoorlockLogsRoute: PrivateAdminDoorlockLogsRoute,
  PrivateAdminNavigatorBuildingsRoute: PrivateAdminNavigatorBuildingsRoute,
  PrivateAdminNavigatorClassroomTypesRoute:
    PrivateAdminNavigatorClassroomTypesRoute,
  PrivateAdminNavigatorClassroomsRoute: PrivateAdminNavigatorClassroomsRoute,
  PrivateAdminNavigatorCorridorsRoute: PrivateAdminNavigatorCorridorsRoute,
  PrivateAdminNavigatorLiftsRoute: PrivateAdminNavigatorLiftsRoute,
  PrivateAdminNavigatorPreviewRoute: PrivateAdminNavigatorPreviewRoute,
  PrivateAdminNavigatorStairsRoute: PrivateAdminNavigatorStairsRoute,
  PrivateAdminNavigatorTranslationsRoute:
    PrivateAdminNavigatorTranslationsRoute,
  PrivateAdminNewsAnnouncementsRoute: PrivateAdminNewsAnnouncementsRoute,
  PrivateAdminNewsSystemMessagesRoute: PrivateAdminNewsSystemMessagesRoute,
  PrivateAdminTimetableImportRoute: PrivateAdminTimetableImportRoute,
  PrivateAdminTimetableManageRoute: PrivateAdminTimetableManageRoute,
  PrivateAdminTimetableMovedLessonsRoute:
    PrivateAdminTimetableMovedLessonsRoute,
  PrivateAdminTimetableSubstitutionsRoute:
    PrivateAdminTimetableSubstitutionsRoute,
  PrivateAdminTimetableTeachersRoute: PrivateAdminTimetableTeachersRoute,
  PrivateAdminDoorlockIndexRoute: PrivateAdminDoorlockIndexRoute,
  PrivateAdminNavigatorIndexRoute: PrivateAdminNavigatorIndexRoute,
}

const PrivateAdminRouteRouteWithChildren =
  PrivateAdminRouteRoute._addFileChildren(PrivateAdminRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateAdminRouteRoute: typeof PrivateAdminRouteRouteWithChildren
  PrivateSettingsRoute: typeof PrivateSettingsRoute
  PrivateCardsIndexRoute: typeof PrivateCardsIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAdminRouteRoute: PrivateAdminRouteRouteWithChildren,
  PrivateSettingsRoute: PrivateSettingsRoute,
  PrivateCardsIndexRoute: PrivateCardsIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicPolicyRoute: typeof PublicPolicyRoute
  PublicSubsRoute: typeof PublicSubsRoute
  PublicUnsubscribeRoute: typeof PublicUnsubscribeRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicPolicyRoute: PublicPolicyRoute,
  PublicSubsRoute: PublicSubsRoute,
  PublicUnsubscribeRoute: PublicUnsubscribeRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
